export enum JobStatus {
  CONFIRMED = 'CONFIRMED',
  IN_QUEUE = 'IN_QUEUE',
  RECEIVED = 'RECEIVED',
  URL_SCRAPING_STARTED = 'URL_SCRAPING_STARTED',
  GOOGLE_SCRAPING_STARTED = 'GOOGLE_SCRAPING_STARTED',
  ANALYSIS_STARTED = 'ANALYSIS_STARTED',
  SAVING = 'SAVING',
  COMPLETED = 'COMPLETED',
}
